version: "3.6"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  graphql-engine:
    image: ${HASURA_DOCKER_IMAGE:-hasura/graphql-engine:v2.0.9.cli-migrations-v3}
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: "no"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
      ACTION_BASE_URL: ${ACTION_BASE_URL}
      CACHES_BASE_URL: ${CACHES_BASE_URL}
      REALTIME_BASE_URL: ${REALTIME_BASE_URL}
      PLAYOUT_BASE_URL: ${PLAYOUT_BASE_URL}
      EVENT_SECRET: ${EVENT_SECRET}
      PRESENCE_FLUSH_SECRET: ${PRESENCE_FLUSH_SECRET}
      PRESENCE_SUMMARY_SECRET: ${PRESENCE_SUMMARY_SECRET}
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_GRAPHQL_AUTH_HOOK}
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
  rabbitmq:
    image: rabbitmq:3.8.14-management
    hostname: rabbitmq-1
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq/enabled-plugins.erl:/etc/rabbitmq/enabled_plugins
