version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      # TODO: set up Postgres security
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - "postgres"
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  redis:
    image: redis
    ports:
      - "6379:6379"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.6.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      ACTION_BASE_URL: ${ACTION_BASE_URL}
      REALTIME_BASE_URL: ${PRESENCE_BASE_URL}
      PLAYOUT_BASE_URL: ${PLAYOUT_BASE_URL}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
      EVENT_SECRET: ${EVENT_SECRET}
      PRESENCE_FLUSH_SECRET: ${PRESENCE_FLUSH_SECRET}
      PRESENCE_SUMMARY_SECRET: ${PRESENCE_SUMMARY_SECRET}
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
  rabbitmq:
      image: rabbitmq:3.8.14-management
      hostname: rabbitmq-1
      ports:
          - "5672:5672"
          - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
      volumes:
          - ./rabbitmq/enabled-plugins.erl:/etc/rabbitmq/enabled_plugins
volumes:
  db_data:
