name: Hasura CI/CD - Testing

on:
  push:
    branches:
      - develop

jobs:
  deploy-hasura:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hasura CI/CD
        uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          PATH_TO_HASURA_PROJECT_ROOT: ./hasura
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_PERSONAL_ACCESS_TOKEN: ${{ secrets.HASURA_PERSONAL_ACCESS_TOKEN }}
          HASURA_PROJECT_ID: ${{ secrets.HASURA_PROJECT_ID }}
          # If you want to disable either migrations or regression tests, make sure to remove them completely
          # The script only checks for their presence, not their value
          HASURA_MIGRATIONS_ENABLED: true
          ACTION_BASE_URL: ${{ secrets.ACTION_BASE_URL }}
          REALTIME_BASE_URL: ${{ secrets.REALTIME_BASE_URL }}
          # TODO: Regression testing - but apply this in a second job after services have been re-deployed
          # HASURA_REGRESSION_TESTS_ENABLED: true
          # HASURA_REGRESSION_TESTSUITE_ID: xxxxxx-xxx-xxxx-xxxxx-xxxxxx
